In [1]:
import pandas as pd
import re
from nltk.tokenize import RegexpTokenizer

In [137]:
dataset = pd.read_csv('data/keywords_.csv', sep=';')

In [138]:
df = pd.DataFrame(dataset)
df

,'AdGroupId','CampaignId','Id','Keyword','ServingStatus','State','Status','StrategyPriority'
0,3767436593,42244009,16348493015,'фас тарифы -жкх','ELIGIBLE','ON','ACCEPTED','NORMAL'
1,3767436593,42244009,16348696779,'фас тарифы жкх','ELIGIBLE','ON','ACCEPTED','NORMAL'
2,3767470344,42244009,16348696780,'определение суд экспертизы','ELIGIBLE','ON','ACCEPTED','NORMAL'
3,3767470344,42244009,16348696782,'определение суда +о назначении экспертизы','ELIGIBLE','ON','ACCEPTED','NORMAL'
4,3767470345,42244009,16348696783,'жкх последние изменения','ELIGIBLE','ON','ACCEPTED','NORMAL'
...,...,...,...,...,...,...,...,...
3995,3126857265,26790451,13056964783,'DC Shoes Banshee','ELIGIBLE','ON','ACCEPTED','NORMAL'
3996,3126857265,26790451,13056964790,'Shoes Banshee -dc','ELIGIBLE','ON','ACCEPTED','NORMAL'
3997,3126857265,26790451,13056964798,'686 Mannual Standard -w','ELIGIBLE','ON','ACCEPTED','NORMAL'
3998,3126857265,26790451,13056964806,'686 Mannual Standard W','ELIGIBLE','ON','ACCEPTED','NORMAL'
3999,3126857265,26790451,13056964814,'Burton Gloria -брюки','ELIGIBLE','ON','ACCEPTED','NORMAL'

In [139]:
df['\'Keyword\''] = list(map(lambda x: re.sub(r'\s-[a-zA-Zа-яА-Я!0-9]+', '', x), df['\'Keyword\'']))

In [140]:
df

,'AdGroupId','CampaignId','Id','Keyword','ServingStatus','State','Status','StrategyPriority'
0,3767436593,42244009,16348493015,'фас тарифы','ELIGIBLE','ON','ACCEPTED','NORMAL'
1,3767436593,42244009,16348696779,'фас тарифы жкх','ELIGIBLE','ON','ACCEPTED','NORMAL'
2,3767470344,42244009,16348696780,'определение суд экспертизы','ELIGIBLE','ON','ACCEPTED','NORMAL'
3,3767470344,42244009,16348696782,'определение суда +о назначении экспертизы','ELIGIBLE','ON','ACCEPTED','NORMAL'
4,3767470345,42244009,16348696783,'жкх последние изменения','ELIGIBLE','ON','ACCEPTED','NORMAL'
...,...,...,...,...,...,...,...,...
3995,3126857265,26790451,13056964783,'DC Shoes Banshee','ELIGIBLE','ON','ACCEPTED','NORMAL'
3996,3126857265,26790451,13056964790,'Shoes Banshee','ELIGIBLE','ON','ACCEPTED','NORMAL'
3997,3126857265,26790451,13056964798,'686 Mannual Standard','ELIGIBLE','ON','ACCEPTED','NORMAL'
3998,3126857265,26790451,13056964806,'686 Mannual Standard W','ELIGIBLE','ON','ACCEPTED','NORMAL'
3999,3126857265,26790451,13056964814,'Burton Gloria','ELIGIBLE','ON','ACCEPTED','NORMAL'

In [141]:
df_result = pd.DataFrame({'Keyword_x' : kw_x, 'AdGroupId_x' : agi_x, 'Keyword_y' : kw_y, 'AdGroupId_y' : agi_y, 'crossed' : crossed})

In [142]:
frame = list()
tokenizer = RegexpTokenizer(r'[a-zA-Zа-яА-Я+!0-9]+')
for i in df.index:
    agi = df['\'AdGroupId\''][i]
    series = df.where(df['\'AdGroupId\''] != agi)
    series.dropna(inplace=True)
    for s in series.index:
        word_x = df['\'Keyword\''][i]
        word_y = df['\'Keyword\''][s]
        kws_x = tokenizer.tokenize(word_x.lower())
        kws_y = tokenizer.tokenize(word_y.lower())
        agiy = df['\'AdGroupId\''][s]
        subset = [word for word in kws_x if word.lower() in kws_y]
        if len(subset) > 1:
            subset = ', '.join(map(str, subset))
            frame.append(pd.DataFrame({'Keyword_x' : [word_x], 'AdGroupId_x' : [agi], 'Keyword_y' : [word_y], 
                                       'AdGroupId_y' : [agiy], 'crossed' : [subset]}))

KeyboardInterrupt:

In [143]:
df_result = pd.concat(frame)
df_result

,Keyword_x,AdGroupId_x,Keyword_y,AdGroupId_y,crossed
0,'определение суд экспертизы',3767470344,'суд экспертизы рф',3767470352,"суд, экспертизы"
0,'изменения +в жкх',3767470345,'жкх подали +в суд',3767470351,"+в, жкх"
0,'оплата жкх',3767470346,'оплата коммунальных услуг жкх',3767470348,"оплата, жкх"
0,'стоимость услуг жкх',3767470346,'оплата коммунальных услуг жкх',3767470348,"услуг, жкх"
0,'стоимость услуг жкх',3767470346,'аудиторская компания стоимость услуг',3767585626,"стоимость, услуг"
...,...,...,...,...,...
0,'куплю однокомнатную квартиру +в мотовилихинск...,3856120657,'куплю 1 комнатную квартиру +от пзсп пермь',2379001678,"куплю, квартиру"
0,'куплю однокомнатную квартиру +в мотовилихинск...,3856120657,'купить земельный участок +в пермском районе',2461777262,"+в, районе"
0,'куплю однокомнатную квартиру +в мотовилихинск...,3856120657,'купить +в новостройке квартиру +под ключ',2183766086,"квартиру, +в"
0,'куплю однокомнатную квартиру +в мотовилихинск...,3856120657,'купить 3 х комнатную квартиру +в новостройке',2279736696,"квартиру, +в"
0,'куплю однокомнатную квартиру +в мотовилихинск...,3856120657,'куплю 1 комнатную квартиру +от пзсп пермь',2183766076,"куплю, квартиру"

In [144]:
df_result.to_csv(r'data/keywords_ext.csv', index=None)